
---
dist: bionic
language: minimal

cache:
  directories:
    - /home/travis/.vagrant.d/boxes

jobs:
  include:

    - stage: build
      install:
        - sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev
        - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
        - sudo dpkg -i vagrant_2.2.9_x86_64.deb
        - sudo vagrant plugin install vagrant-libvirt vagrant-scp vagrant-reload
      script:
        - cp -v salt/etc/minion{.example,}
        - cp -v vagrant/examples/Vagrantfile.generic-box.centos-7.x86_64.example vagrant/Vagrantfile.generic-box
        - travis_wait sudo vagrant up --provider=libvirt generic-box
        - sudo vagrant destroy --force generic-box

    - stage: release
      install:
        - wget https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh
        - sudo bash install.sh
        - nvm install lts/*
        - npm i -D semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/npm @semantic-release/github @semantic-release/git @semantic-release/exec @commitlint/cli @commitlint/config-conventional
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
        on:
          all_branches: true 

notifications:
  slack:
    secure: b7jnaH71TgVPeXRfhnC8S41dfIvPBJ1W/1xPlk02EPA8cTrErUSlS9x/Dhb1bqSYrukcZwdnxkjakjP3jUecvMD5KWqYwmCEMSDkZXsWTlFRQxYennKOUyWzhm+5TDUpICdhY/LmlvTWnMHrvCI0JpzhrtnrCGSbpA1qp6W10h7yLPMLxaLG9W6qFzlf7Rl1/3Cc0Iow4N4Poawbgcr/Z8iZSkwtCPOO7Enu9gYT3xKXWMdJuvQxVZOwjTUaBj5lxacg+u/h7K+hrhIKNq7hP36bp3QAMwu9wsWx4HS0D/CuL176eooJrnlCVKqBGRYV71t2wBPzQ64zRcEl5UZve5J0+S2A8279GQXMUjRvLKxWXjQMIal6hBxKetAO6j5mIBfJqBSXEqhwzZTTRIiG/vT+8mYtQQHOymHzvtxrIhl8Xgjkch7Z/ugd71HKPlo6Amzc975QdbuO9lKk9nLPeRiwKYJy0mBG7ikHZwtpggUWohFc3F0V6HRCoQz4Wgj5AfQRsczQUEvnhyN35xX9VwySbi416sp3kKVg1QIii5QzE84F3i5mwl1QyNmo3BeW0CAcNfbAG6J4kCqU64NQ2OduzIj9lnnqidGJoiMQ+A1wj+bCktkAX+YhbnZNEI3BCq1EYRb/C+Of1XkTlLka1qTHzebxlxLBolmBlOmD0dE=
