os: Ubuntu2004
platform:
  - x64
install:
  - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
  - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
  - sudo apt update && sudo apt install --allow-unauthenticated -y vagrant qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils ruby-dev libvirt-dev
  - sudo vagrant plugin install vagrant-libvirt vagrant-scp vagrant-reload vagrant-vbguest
build_script:
  - cp -v salt/etc/minion{.example,}
  - cp -v vagrant/examples/Vagrantfile.generic-box.almalinux-8-5.x86_64.example vagrant/Vagrantfile.generic-box
  - sudo vagrant up --provider=libvirt generic-box
  - sudo vagrant destroy --force generic-box
on_success:
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.37.2/install.sh
  - sudo bash install.sh
  - nvm install lts/*
  - npm i -D semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/npm @semantic-release/github @semantic-release/git @semantic-release/exec @commitlint/cli @commitlint/config-conventional
  - npx semantic-release
test: off
